from collections.abc import Iterable, Sequence
from typing import Any

class Table:
    def count_rows(self) -> int: ...
    def to_list(self, limit: int | None = None) -> list[dict]: ...
    def head(self, limit: int) -> Any: ...
    def add(self, records: Iterable[Any]) -> None: ...
    def delete(self, clause: str) -> None: ...
    def update(self, where: str, values: dict) -> None: ...
    def search(self, q: Any) -> Any: ...

class LanceDB:
    def table_names(self) -> Sequence[str]: ...
    def open_table(self, name: str) -> Table: ...
    def create_table(self, name: str, schema: Any = None, mode: str | None = None, **kwargs) -> Table: ...

def connect(path: str) -> LanceDB: ...
