from collections.abc import Iterator
from typing import Any

class Rdict:
    def __init__(self, path: str) -> None: ...
    def items(self) -> Iterator[tuple[bytes, bytes]]: ...
    def get(self, key: bytes, default: Any = None) -> Any: ...
    def __setitem__(self, key: bytes, value: bytes) -> None: ...
    def __delitem__(self, key: bytes) -> None: ...
