from typing import Any, Iterator, Tuple

class Rdict:
    def __init__(self, path: str) -> None: ...
    def items(self) -> Iterator[Tuple[bytes, bytes]]: ...
    def get(self, key: bytes, default: Any = None) -> Any: ...
    def __setitem__(self, key: bytes, value: bytes) -> None: ...
    def __delitem__(self, key: bytes) -> None: ...
