from typing import Any, Iterator, Tuple

class Options: ...
class CompressionType:
    lz4_compression: int

class BlockBasedTableOptions: ...
class LRUCache: ...
class BloomFilterPolicy:
    def __init__(self, bits: int) -> None: ...
class BlockBasedTableFactory:
    def __init__(self, opts: BlockBasedTableOptions) -> None: ...

class DB:
    def __init__(self, path: str, opts: Options) -> None: ...
    def get(self, key: bytes) -> Any: ...
    def put(self, key: bytes, value: bytes) -> None: ...
    def delete(self, key: bytes) -> None: ...
    def iteritems(self) -> Iterator[Tuple[bytes, bytes]]: ...
